SET NAMES utf8mb4;
START TRANSACTION;

CREATE TABLE changelog (
 id INT UNSIGNED NOT NULL PRIMARY KEY,
 timestamp INT UNSIGNED
);
INSERT INTO changelog VALUES (1, UNIX_TIMESTAMP());


CREATE TABLE todo ( 
  id INT UNSIGNED NOT NULL PRIMARY KEY,
  list_id CHAR(6) NOT NULL,

  title VARCHAR(200) NOT NULL,

  created_at INT UNSIGNED NOT NULL,
  modified_at INT UNSIGNED NOT NULL,

  status TINYINT NOT NULL,
  completed_at INT UNSIGNED
);

COMMIT;
